# Generated by Django 4.0.2 on 2022-03-15 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0003_alter_menuitem_restaurant_alter_restaurant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnts_restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imgs_restaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
