# Generated by Django 4.0.2 on 2022-03-15 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_comment_date_alter_comment_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmnts_restaurant', to='restaurants.restaurant'),
        ),
    ]
