# Generated by Django 4.0.2 on 2022-03-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_comment_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='restaurant',
            field=models.IntegerField(null=True),
        ),
    ]
