# Generated by Django 4.0.2 on 2022-03-16 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantimage',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imgs_restaurant', to='restaurants.restaurant'),
        ),
    ]
