# Generated by Django 4.0.2 on 2022-03-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_restaurantimage_restaurant'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'restaurant'), name='unique_follow'),
        ),
    ]
