# Generated by Django 4.0.2 on 2022-03-16 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='follower',
            new_name='likedby',
        ),
    ]
