# Generated by Django 4.0.2 on 2022-03-16 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_date'),
        ('restaurants', '0011_rename_follower_like_likedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked_blog', to='blogs.blog'),
        ),
    ]
