# Generated by Django 4.0.2 on 2022-03-16 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_follow_unique_follow'),
        ('restaurants', '0012_like_blog'),
    ]

    operations = [
    ]
