# Generated by Django 4.0.2 on 2022-03-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_remove_like_blog_alter_like_likedby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='liked_by',
        ),
    ]
