# Generated by Django 4.0.2 on 2022-03-15 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('header', models.CharField(max_length=256)),
                ('subtext', models.CharField(max_length=256)),
                ('body', models.TextField()),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_restaurant', to='restaurants.restaurant')),
            ],
        ),
    ]
